# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
new= "retrieved_cities.csv"

In [3]:
df=pd.read_csv(new)
df.head(30)

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,Upernavik,100,GL,1584220116,97,72.79,-56.15,-10.35,3.56
1,Bluff,100,NZ,1584219913,81,-46.60,168.33,55.99,3.00
2,Ushuaia,20,AR,1584220085,47,-54.80,-68.30,55.40,6.93
3,Mergen,25,CN,1584220117,84,49.18,125.22,-0.63,11.99
4,Airai,18,TL,1584220117,83,-8.93,125.41,63.99,2.91
5,Sehithwa,84,BW,1584220117,53,-20.47,22.72,79.29,3.11
6,Lebu,0,CL,1584220118,55,-37.62,-73.65,62.73,13.42
7,Thompson,20,CA,1584220118,46,55.74,-97.86,6.80,2.24
8,Tiksi,0,RU,1584220118,80,71.69,128.87,-16.11,8.46
9,Yellowknife,90,CA,1584219607,54,62.46,-114.35,7.00,11.41
10,New Norfolk,75,AU,1584219803,81,-42.78,147.06,53.01,5.82
11,Tuktoyaktuk,90,CA,1584219789,85,69.45,-133.04,21.20,29.97
12,Avarua,37,CK,1584219796,74,-21.21,-159.78,84.20,5.82
13,Chapais,90,CA,1584219819,78,49.78,-74.85,12.20,16.11
14,Vaini,75,TO,1584219788,83,-21.20,-175.20,82.40,13.87
15,Praia da Vit√≥ria,20,PT,1584219859,82,38.73,-27.07,60.80,7.85
16,Bethel,1,US,1584219795,27,41.37,-73.41,55.00,11.41
17,Hong Kong,20,HK,1584219604,52,22.29,114.16,69.01,8.05
18,Punta Arenas,75,CL,1584219789,58,-53.15,-70.92,59.00,20.80
19,Chokurdakh,0,RU,1584219819,97,70.63,147.92,-27.99,2.80
20,Luanda,75,AO,1584219661,78,-8.84,13.23,82.40,9.17
21,Jumla,100,NP,1584220065,94,29.27,82.18,25.65,2.21
22,Busselton,98,AU,1584219793,98,-33.65,115.33,64.99,10.11
23,Dikson,57,RU,1584220120,99,73.51,80.55,-15.75,11.54
24,Khatanga,100,RU,1584219799,88,71.97,102.50,25.29,12.80
25,Nome,100,US,1584219839,99,64.50,-165.41,33.21,4.32
26,Xambio√°,100,BR,1584220121,95,-6.41,-48.54,77.49,3.09
27,Rikitea,0,PF,1584219790,80,-23.12,-134.97,77.67,13.69
28,Fortuna,75,US,1584219798,75,40.60,-124.16,48.99,12.75
29,Castro,0,BR,1584219800,59,-24.79,-50.01,73.17,2.06

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [4]:
# Store latitude and longitude in locations
lat=df["Lat"]
lng=df["Lng"]
coordinates=list(zip(lat,lng))
figure_layout = {
    'width': '400px',
    'height': '300px',
    'border': '1px solid black',
    'padding': '1px',
    'margin': '0 auto 0 auto'
}
fig = gmaps.figure(layout=figure_layout)

In [5]:
heatmap = gmaps.heatmap_layer(coordinates, weights=df["Humidity"])
# Add the layer to the map
fig.add_layer(heatmap)
fig

Figure(layout=FigureLayout(border='1px solid black', height='300px', margin='0 auto 0 auto', padding='1px', wi‚Ä¶

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [6]:
temp=df[df['Max Temp']>85]
wind=temp[temp['Wind Speed']<10]
hotel_df=wind[wind['Cloudiness']>50]
hotel_df.dropna()

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
241,Pozo Colorado,80,PY,1584220156,29,-23.49,-58.80,98.73,3.11
250,La Santisima Trinidad,75,BO,1584220157,63,-14.83,-64.90,91.40,3.36
409,Bida,100,NG,1584220180,17,9.08,6.02,87.39,1.63
459,Grand-Santi,100,GF,1584219879,33,4.25,-54.38,94.77,5.17
478,Puerto Carre√±o,67,CO,1584220189,34,6.19,-67.49,96.75,7.47
480,Upata,98,VE,1584219869,44,8.01,-62.40,87.21,2.84
500,Boca do Acre,100,BR,1584220194,54,-8.75,-67.40,90.99,0.67

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [7]:
import json
# create new col for new information
hotel_df['Hotel Name']=''
hotel_df['Hotel Log']=''
hotel_df['Hotel Lng']=''

/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [8]:
# set up a parameters dictionary

params = {
    "location": '',
    "radius": 5000,
    "type": 'lodging',
    "key": g_key
}

# base url
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

for index,row in hotel_df.iterrows():
    print(row.Lat,row.Lng)
    params['location']=str(row.Lat)+","+str(row.Lng)
    response = requests.get(base_url, params)    
    data = response.json()
    try:
        Hotel = data["results"][0]
        City=data["results"][0]
        latlng=data["results"][0]['geometry']['location']
        
    except:
        print("No major airport")
    else:
        hotel_df.loc[index, "Hotel Name"] = Hotel.get("name", np.nan)
        hotel_df.loc[index, "Hotel Log"] = latlng.get('lat', np.nan)
        hotel_df.loc[index, "Hotel Lng"] = latlng.get('lng', np.nan)

-23.49 -58.8

/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages/pandas/core/indexing.py:965: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

-14.83 -64.9
9.08 6.02
4.25 -54.38
6.19 -67.49
8.01 -62.4
-8.75 -67.4

In [11]:
hotel_df

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed,Hotel Name,Hotel Log,Hotel Lng
241,Pozo Colorado,80,PY,1584220156,29,-23.49,-58.80,98.73,3.11,Hospedaje la Amistad,-23.493,-58.7964
250,La Santisima Trinidad,75,BO,1584220157,63,-14.83,-64.90,91.40,3.36,Hotel Piesta,-14.8344,-64.9017
409,Bida,100,NG,1584220180,17,9.08,6.02,87.39,1.63,Royal Suite,9.06197,5.99738
459,Grand-Santi,100,GF,1584219879,33,4.25,-54.38,94.77,5.17,Hotel La Villa Couacou,4.25073,-54.3822
478,Puerto Carre√±o,67,CO,1584220189,34,6.19,-67.49,96.75,7.47,Casa Hotel Victoria,6.18885,-67.4836
480,Upata,98,VE,1584219869,44,8.01,-62.40,87.21,2.84,Posada Villa Nela,8.00002,-62.3791
500,Boca do Acre,100,BR,1584220194,54,-8.75,-67.40,90.99,0.67,Hotel Linhares,-8.75161,-67.3997

In [9]:
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Hotel Log", "Hotel Lng"]]

In [10]:
hotel_lat=hotel_df["Hotel Log"]
hotel_lng=hotel_df["Hotel Lng"]
hotel_coordinates=list(zip(hotel_lat,hotel_lng))
markers = gmaps.marker_layer(hotel_coordinates,info_box_content=hotel_info)
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(border='1px solid black', height='300px', margin='0 auto 0 auto', padding='1px', wi‚Ä¶